In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('BMI.csv')

In [3]:
df.head()

Gender  Height  Weight  Index
0    Male     174      96      4
1    Male     189      87      2
2  Female     185     110      4
3  Female     195     104      3
4    Male     149      61      3

In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["Gender"]=le.fit_transform(df.Gender)
df.head()

Gender  Height  Weight  Index
0       1     174      96      4
1       1     189      87      2
2       0     185     110      4
3       0     195     104      3
4       1     149      61      3

In [5]:
from sklearn.model_selection import train_test_split
x = df[["Gender","Height","Weight"]]
y = df.Index
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1,shuffle=True)

In [6]:
from sklearn.svm import LinearSVC
svc=LinearSVC()
svc.fit(xtrain,ytrain)

C:\anaconda3\lib\site-packages\sklearn\svm\_base.py:976: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


LinearSVC()

In [7]:
ypred=svc.predict(xtest)

# Model accuracy

### Overfitting & underfitting

In [8]:
#model accuracy ~= test_acc   => Model is ok
#model acc > test_acc => overfitting
#model acc < test_acc => underfitting
from sklearn.metrics import accuracy_score
model_ypred=svc.predict(xtrain)
accuracy_score(ytrain,model_ypred)

0.435

### Test accuracy

In [9]:
from sklearn.metrics import accuracy_score
ypred=svc.predict(xtest)
accuracy_score(ytest,ypred)

0.46

In [10]:
from sklearn.svm import SVC
svc1=SVC(kernel="linear",class_weight=None)
svc1.fit(xtrain,ytrain)


SVC(kernel='linear')

In [11]:
ypred1=svc1.predict(xtest)
accuracy_score(ytest,ypred)

0.46

In [13]:
svc2=SVC(kernel="rbf").fit(xtrain,ytrain)

In [16]:
svc2.score(xtrain,ytrain)

0.83

In [19]:
svc2.score(xtest,ytest)

0.9

In [20]:
svc2=SVC(kernel="poly",degree=3).fit(xtrain,ytrain)

In [21]:
svc2.score(xtrain,ytrain)

0.895

In [22]:
svc2.score(xtest,ytest)

0.9

In [23]:
svc2=SVC(kernel="sigmoid").fit(xtrain,ytrain)

In [24]:
svc2.score(xtrain,ytrain)

0.385

In [25]:
svc2.score(xtest,ytest)

0.44

In [26]:
svc1.support_vectors_

array([[  1., 188.,  54.],
       [  0., 163.,  57.],
       [  1., 181.,  51.],
       [  0., 191.,  54.],
       [  1., 188.,  65.],
       [  0., 195.,  61.],
       [  0., 176.,  54.],
       [  1., 168.,  50.],
       [  1., 184.,  57.],
       [  0., 170.,  53.],
       [  1., 188.,  57.],
       [  0., 148.,  54.],
       [  0., 185.,  81.],
       [  0., 180.,  60.],
       [  0., 163.,  63.],
       [  0., 157.,  60.],
       [  1., 176.,  77.],
       [  0., 191.,  68.],
       [  1., 199.,  99.],
       [  0., 151.,  55.],
       [  0., 192.,  90.],
       [  0., 169.,  88.],
       [  0., 181.,  80.],
       [  0., 153.,  78.],
       [  0., 173.,  82.],
       [  0., 169.,  54.],
       [  1., 165.,  68.],
       [  0., 175.,  83.],
       [  1., 189.,  87.],
       [  0., 160.,  51.],
       [  1., 155.,  57.],
       [  0., 164.,  70.],
       [  0., 184.,  86.],
       [  1., 183., 105.],
       [  0., 162.,  68.],
       [  1., 165.,  80.],
       [  1., 178.,  83.],
 

In [27]:
svc1.support_

array([ 90, 147, 181, 257,   1,  81, 117, 267, 281, 284, 318,  35,  53,
        93, 100, 124, 138, 150, 153, 163, 176, 212, 227, 228, 252, 260,
       279, 291, 358, 367, 391,   3,  42,  43,  59,  74,  85, 102, 141,
       158, 184, 193, 214, 219, 238, 248, 263, 275, 285, 297, 301, 327,
       329, 335, 372, 374, 376, 394,  25,  27,  36,  64,  87, 165, 230,
       237, 243, 245, 258, 274, 280, 304, 319, 330, 333, 355, 365, 370,
       399,  49,  71,  82, 104, 162, 164, 198, 271, 389, 396])

In [28]:
svc1.n_support_

array([ 4,  7, 20, 27, 21, 10])

In [29]:
df.Index.value_counts()

5    198
4    130
2     69
3     68
1     22
0     13
Name: Index, dtype: int64

In [31]:
svc2=SVC(kernel="linear",class_weight="balanced").fit(xtrain,ytrain)
svc2.score(xtrain,ytrain)

0.9475