In [1]:
import pandas as pd
import numpy as np
df=pd.read_csv("E:\\ML\\Housing.csv")
df.head()

Unnamed: 0    price  lotsize  bedrooms  bathrms  stories driveway recroom  \
0           1  42000.0     5850         3        1        2      yes      no   
1           2  38500.0     4000         2        1        1      yes      no   
2           3  49500.0     3060         3        1        1      yes      no   
3           4  60500.0     6650         3        1        2      yes     yes   
4           5  61000.0     6360         2        1        1      yes      no   

  fullbase gashw airco  garagepl prefarea  
0      yes    no    no         1       no  
1       no    no    no         0       no  
2       no    no    no         0       no  
3       no    no    no         0       no  
4       no    no    no         0       no

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 546 entries, 0 to 545
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  546 non-null    int64  
 1   price       546 non-null    float64
 2   lotsize     546 non-null    int64  
 3   bedrooms    546 non-null    int64  
 4   bathrms     546 non-null    int64  
 5   stories     546 non-null    int64  
 6   driveway    546 non-null    object 
 7   recroom     546 non-null    object 
 8   fullbase    546 non-null    object 
 9   gashw       546 non-null    object 
 10  airco       546 non-null    object 
 11  garagepl    546 non-null    int64  
 12  prefarea    546 non-null    object 
dtypes: float64(1), int64(6), object(6)
memory usage: 55.6+ KB


In [3]:
df.isna().sum()

Unnamed: 0    0
price         0
lotsize       0
bedrooms      0
bathrms       0
stories       0
driveway      0
recroom       0
fullbase      0
gashw         0
airco         0
garagepl      0
prefarea      0
dtype: int64

In [4]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
cols=['driveway','recroom','fullbase','gashw','airco','prefarea']
for f in cols:
    df[f]=le.fit_transform(df[f])

In [5]:
df.head()

Unnamed: 0    price  lotsize  bedrooms  bathrms  stories  driveway  \
0           1  42000.0     5850         3        1        2         1   
1           2  38500.0     4000         2        1        1         1   
2           3  49500.0     3060         3        1        1         1   
3           4  60500.0     6650         3        1        2         1   
4           5  61000.0     6360         2        1        1         1   

   recroom  fullbase  gashw  airco  garagepl  prefarea  
0        0         1      0      0         1         0  
1        0         0      0      0         0         0  
2        0         0      0      0         0         0  
3        1         0      0      0         0         0  
4        0         0      0      0         0         0

## Determining x and y from slr

In [6]:
df.corr()

Unnamed: 0     price   lotsize  bedrooms   bathrms   stories  \
Unnamed: 0    1.000000  0.376007  0.374338  0.114219  0.108395  0.231427   
price         0.376007  1.000000  0.535796  0.366447  0.516719  0.421190   
lotsize       0.374338  0.535796  1.000000  0.151851  0.193833  0.083675   
bedrooms      0.114219  0.366447  0.151851  1.000000  0.373769  0.407974   
bathrms       0.108395  0.516719  0.193833  0.373769  1.000000  0.324066   
stories       0.231427  0.421190  0.083675  0.407974  0.324066  1.000000   
driveway      0.314014  0.297167  0.288778 -0.011996  0.041955  0.122499   
recroom       0.096721  0.254960  0.140327  0.080492  0.126892  0.042281   
fullbase     -0.002034  0.186218  0.047487  0.097201  0.102791 -0.173860   
gashw        -0.033494  0.092837 -0.009201  0.046028  0.067365  0.018261   
airco         0.157111  0.453347  0.221765  0.160412  0.184955  0.296216   
garagepl      0.125326  0.383302  0.352872  0.139117  0.178178  0.043412   
prefarea      0.519994  0.329074  0.234782  0.078953  0.064013  0.042940   

            driveway   recroom  fullbase     gashw     airco  garagepl  \
Unnamed: 0  0.314014  0.096721 -0.002034 -0.033494  0.157111  0.125326   
price       0.297167  0.254960  0.186218  0.092837  0.453347  0.383302   
lotsize     0.288778  0.140327  0.047487 -0.009201  0.221765  0.352872   
bedrooms   -0.011996  0.080492  0.097201  0.046028  0.160412  0.139117   
bathrms     0.041955  0.126892  0.102791  0.067365  0.184955  0.178178   
stories     0.122499  0.042281 -0.173860  0.018261  0.296216  0.043412   
driveway    1.000000  0.091959  0.043428 -0.011942  0.106290  0.203682   
recroom     0.091959  1.000000  0.372434 -0.010119  0.136626  0.038122   
fullbase    0.043428  0.372434  1.000000  0.004677  0.045248  0.052524   
gashw      -0.011942 -0.010119  0.004677  1.000000 -0.130350  0.068144   
airco       0.106290  0.136626  0.045248 -0.130350  1.000000  0.156596   
garagepl    0.203682  0.038122  0.052524  0.068144  0.156596  1.000000   
prefarea    0.199378  0.161292  0.228651 -0.059170  0.115626  0.092364   

            prefarea  
Unnamed: 0  0.519994  
price       0.329074  
lotsize     0.234782  
bedrooms    0.078953  
bathrms     0.064013  
stories     0.042940  
driveway    0.199378  
recroom     0.161292  
fullbase    0.228651  
gashw      -0.059170  
airco       0.115626  
garagepl    0.092364  
prefarea    1.000000

In [7]:
x=df[['lotsize']]
y=df.price

In [8]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2,random_state=1,shuffle=True)


## Dividing into Train and TEst

In [9]:
print(xtrain.shape)
print(ytrain.shape)
print(xtest.shape)
print(ytest.shape)

(436, 1)
(436,)
(110, 1)
(110,)


# Building a Simple Linear Regression model

In [10]:
from sklearn.linear_model import LinearRegression
slr = LinearRegression()
slr.fit(xtrain,ytrain)

LinearRegression()

In [11]:
slr.coef_
#6.58 lotsize(it's a x value )

array([6.58783799])

In [12]:
slr.intercept_

33713.50794419724

# Evaluation

In [13]:
ypred = slr.predict(xtest)

In [14]:
ypred

array([ 62370.60319904,  73635.80616129,  56441.54900838,  86284.45510136,
        65862.15733354,  74913.84673128,  57429.72470683,  54069.92733212,
        69287.83308814,  77193.23867568,  52620.6029744 ,  99328.3743208 ,
        49721.95425897,  81936.48202821,  73240.53588191,  72252.36018347,
        63358.77889748,  48042.05557162, 120672.96940717, 101172.9689579 ,
        79828.37387153,  92180.57010207, 101963.50951665,  60064.85990267,
        64320.60324397,  52884.11649399,  60591.88694184,  57956.751746  ,
        69946.6168871 ,  81350.16444713,  63490.53565728,  59076.68420423,
        93004.04985077,  56902.69766766,  46559.79202395,  47844.42043193,
        63424.65727738,  65993.91409333,  56243.91386869,  52159.45431513,
        73240.53588191,  62172.96805935,  71264.18448503,  64017.56269645,
        75612.15755818,  47844.42043193,  89051.347057  ,  56770.94090786,
        56507.42738828,  56639.18414807,  77193.23867568,  57693.23822641,
        65433.94786421,  

In [15]:
from sklearn.metrics import mean_absolute_error,r2_score
print(mean_absolute_error(ytest,ypred))
print(r2_score(ytest,ypred))
#28 % only accuracy %

16667.48175714164
0.2838357590291908


# Prediction

In [16]:
xnew=np.array([5000]).reshape(1,-1)
slr.predict(xnew)

array([66652.69789229])